-- Promoção: desconto aplicado automaticamente a um grupo de clientes (com
-- requisito opcional, ex: gasto mínimo acumulado) ou a todos, numa janela de validade.
CREATE TABLE promocoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(300),
    tipo_desconto VARCHAR(10) NOT NULL CHECK (tipo_desconto IN ('PERCENTUAL','FIXO')),
    valor_desconto NUMERIC(10,2) NOT NULL CHECK (valor_desconto > 0),
    tipo_alvo VARCHAR(8) NOT NULL CHECK (tipo_alvo IN ('TODOS','GRUPO')),
    grupo_cliente_id BIGINT REFERENCES grupos_clientes (id),
    -- null = sem requisito extra além de pertencer ao grupo/todos; valor = gasto
    -- histórico acumulado mínimo, calculado e informado pelo order-service (catalog
    -- não tem acesso a pedidos/comandas).
    requisito_gasto_minimo NUMERIC(10,2),
    valido_de DATE NOT NULL,
    valido_ate DATE NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CHECK (valido_ate >= valido_de)
);

CREATE INDEX idx_promocoes_restaurante_ativo ON promocoes (restaurante_id, ativo);
