-- CRM básico de clientes do restaurante (base pra cupom/promoção segmentados).
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(150),
    data_nascimento DATE,
    endereco_rua VARCHAR(200),
    endereco_numero VARCHAR(20),
    endereco_bairro VARCHAR(100),
    endereco_cidade VARCHAR(100),
    endereco_complemento VARCHAR(100),
    endereco_cep VARCHAR(9),
    observacoes TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_clientes_restaurante_id ON clientes (restaurante_id);

-- Dedupe por telefone dentro do mesmo restaurante (busca rápida no PDV por telefone).
CREATE UNIQUE INDEX uq_clientes_restaurante_telefone ON clientes (restaurante_id, telefone);
