-- Grupo de clientes (segmentação manual, ex: "VIP") usado por Cupom/Promoção.
-- Não confundir com "grupos" de auth-service, que é RBAC de equipe.
CREATE TABLE grupos_clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(300),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_grupos_clientes_restaurante_id ON grupos_clientes (restaurante_id);

-- Associação manual cliente<->grupo: admin adiciona/remove um a um.
CREATE TABLE grupo_cliente_membros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    grupo_cliente_id BIGINT NOT NULL REFERENCES grupos_clientes (id),
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    adicionado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_grupo_cliente_membro ON grupo_cliente_membros (grupo_cliente_id, cliente_id);
CREATE INDEX idx_grupo_cliente_membros_cliente_id ON grupo_cliente_membros (cliente_id);
