-- Saldo de estoque por produto. Tabela própria (não colunas em produtos) pra
-- isolar essa preocupação e permitir seu próprio histórico de movimentação.
CREATE TABLE estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL REFERENCES produtos (id),
    quantidade INTEGER NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
    quantidade_minima INTEGER NOT NULL DEFAULT 0 CHECK (quantidade_minima >= 0),
    -- controlado=false: produto fora do controle de estoque (nunca bloqueia/baixa venda).
    controlado BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_estoque_produto ON estoque (produto_id);
CREATE INDEX idx_estoque_restaurante_id ON estoque (restaurante_id);
