-- Histórico/auditoria de toda mudança de saldo de estoque (manual ou por venda).
CREATE TABLE movimentacoes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL REFERENCES produtos (id),
    tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('ENTRADA','SAIDA','AJUSTE','VENDA','ESTORNO')),
    quantidade INTEGER NOT NULL, -- delta assinado efetivamente aplicado
    quantidade_resultante INTEGER NOT NULL, -- estoque.quantidade após este movimento (snapshot p/ auditoria)
    motivo VARCHAR(300),
    -- "pedido:123" quando tipo=VENDA/ESTORNO (correlação com order-service); null p/ movimentos manuais.
    referencia_externa VARCHAR(50),
    criado_por_id BIGINT,
    criado_por_nome VARCHAR(100),
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_mov_estoque_produto_criado_em ON movimentacoes_estoque (produto_id, criado_em DESC);
CREATE INDEX idx_mov_estoque_restaurante_id ON movimentacoes_estoque (restaurante_id);
