-- Combo: junção de 2+ produtos vendidos juntos por um preço fixo, pra todos os clientes.
CREATE TABLE combos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(300),
    preco NUMERIC(10,2) NOT NULL CHECK (preco > 0),
    imagem_base64 TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_combos_restaurante_id ON combos (restaurante_id);

CREATE TABLE combo_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combo_id BIGINT NOT NULL REFERENCES combos (id),
    produto_id BIGINT NOT NULL REFERENCES produtos (id),
    quantidade INTEGER NOT NULL DEFAULT 1 CHECK (quantidade > 0)
);

CREATE UNIQUE INDEX uq_combo_item_produto ON combo_itens (combo_id, produto_id);
CREATE INDEX idx_combo_itens_combo_id ON combo_itens (combo_id);
-- Regra "no mínimo 2 produtos distintos por combo" validada em ComboService, não em SQL.
