-- Cupom de desconto: código aplicável a todos, um grupo de clientes ou um
-- cliente individual, dentro de uma janela de validade.
CREATE TABLE cupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    codigo VARCHAR(30) NOT NULL,
    tipo_desconto VARCHAR(10) NOT NULL CHECK (tipo_desconto IN ('PERCENTUAL','FIXO')),
    valor_desconto NUMERIC(10,2) NOT NULL CHECK (valor_desconto > 0),
    tipo_alvo VARCHAR(12) NOT NULL CHECK (tipo_alvo IN ('TODOS','GRUPO','INDIVIDUAL')),
    grupo_cliente_id BIGINT REFERENCES grupos_clientes (id),
    cliente_id BIGINT REFERENCES clientes (id),
    valido_de DATE NOT NULL,
    valido_ate DATE NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CHECK (valido_ate >= valido_de)
);

-- Código normalizado (uppercase) na aplicação antes de salvar/consultar.
CREATE UNIQUE INDEX uq_cupons_restaurante_codigo ON cupons (restaurante_id, codigo);
CREATE INDEX idx_cupons_restaurante_ativo ON cupons (restaurante_id, ativo);
-- grupo_cliente_id obrigatório sse tipo_alvo=GRUPO, cliente_id obrigatório sse
-- tipo_alvo=INDIVIDUAL: validado em CupomService (não expressável limpo em CHECK
-- cross-column com FK opcional).
