server:
  port: 8085

spring:
  application:
    name: notification-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:comanda_digital_super_secret_key_2024_must_be_at_least_32_chars}

management:
  endpoints:
    web:
      exposure:
        include: health,info
