-- Taxas da maquininha de cartão — usadas pro caixa saber o líquido recebido
-- por venda no crédito/débito (informativo, não bloqueia a venda).
ALTER TABLE restaurante_configs ADD COLUMN taxa_debito NUMERIC(5,2) NOT NULL DEFAULT 0;
ALTER TABLE restaurante_configs ADD COLUMN taxa_credito_vista NUMERIC(5,2) NOT NULL DEFAULT 0;
ALTER TABLE restaurante_configs ADD COLUMN taxa_credito_parcelado NUMERIC(5,2) NOT NULL DEFAULT 0;

-- Sessão de caixa (abrir/fechar) — controla o turno de operação do PDV.
CREATE TABLE sessoes_caixa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    aberto_por_id BIGINT NOT NULL,
    aberto_por_nome VARCHAR(100) NOT NULL,
    valor_abertura NUMERIC(10,2) NOT NULL,
    aberto_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    fechado_por_id BIGINT,
    fechado_por_nome VARCHAR(100),
    valor_fechamento NUMERIC(10,2),
    fechado_em TIMESTAMP(6) WITHOUT TIME ZONE,
    status VARCHAR(10) NOT NULL DEFAULT 'ABERTO' CHECK (status IN ('ABERTO', 'FECHADO'))
);

CREATE INDEX idx_sessoes_caixa_restaurante_status ON sessoes_caixa (restaurante_id, status);
