-- Baseline gerada a partir de pg_dump --schema-only real (oia-postgres/db_order), substituindo a versao inferida anterior.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comandas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comandas (
    id bigint NOT NULL,
    closed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    garcon_id bigint NOT NULL,
    garcon_nome character varying(100) NOT NULL,
    mesa_id bigint NOT NULL,
    mesa_numero integer NOT NULL,
    metodo_pagamento character varying(255),
    parcelas integer,
    restaurante_id bigint NOT NULL,
    status character varying(255),
    CONSTRAINT comandas_metodo_pagamento_check CHECK (((metodo_pagamento)::text = ANY ((ARRAY['DINHEIRO'::character varying, 'PIX'::character varying, 'CARTAO_CREDITO'::character varying, 'CARTAO_DEBITO'::character varying])::text[]))),
    CONSTRAINT comandas_status_check CHECK (((status)::text = ANY ((ARRAY['ABERTA'::character varying, 'AGUARDANDO_PAGAMENTO'::character varying, 'FECHADA'::character varying])::text[])))
);


--
-- Name: comandas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comandas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comandas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entregas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entregas (
    id bigint NOT NULL,
    cliente_nome character varying(100) NOT NULL,
    cliente_telefone character varying(20),
    created_at timestamp(6) without time zone,
    endereco_bairro character varying(100),
    endereco_cidade character varying(100) NOT NULL,
    endereco_complemento character varying(100),
    endereco_numero character varying(20) NOT NULL,
    endereco_rua character varying(200) NOT NULL,
    entregador_id bigint,
    entregador_nome character varying(100),
    entregue_at timestamp(6) without time zone,
    metodo_pagamento character varying(255) NOT NULL,
    observacao character varying(500),
    origem_whatsapp boolean NOT NULL,
    pagamento_confirmado_caixa boolean NOT NULL,
    parcelas integer,
    pedido_cozinha_id bigint,
    restaurante_id bigint NOT NULL,
    status character varying(255),
    CONSTRAINT entregas_metodo_pagamento_check CHECK (((metodo_pagamento)::text = ANY ((ARRAY['DINHEIRO'::character varying, 'PIX'::character varying, 'CARTAO_CREDITO'::character varying, 'CARTAO_DEBITO'::character varying])::text[]))),
    CONSTRAINT entregas_status_check CHECK (((status)::text = ANY ((ARRAY['AGUARDANDO'::character varying, 'ACEITA'::character varying, 'PRONTO_PARA_ENTREGA'::character varying, 'SAIU_PARA_ENTREGA'::character varying, 'ENTREGUE'::character varying, 'CANCELADA'::character varying])::text[])))
);


--
-- Name: entregas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entregas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entregas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itens_entrega; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.itens_entrega (
    id bigint NOT NULL,
    observacao character varying(255),
    preco_unitario numeric(10,2) NOT NULL,
    produto_id bigint NOT NULL,
    produto_nome character varying(200) NOT NULL,
    quantidade integer NOT NULL,
    entrega_id bigint NOT NULL
);


--
-- Name: itens_entrega_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.itens_entrega ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_entrega_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itens_pedido; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.itens_pedido (
    id bigint NOT NULL,
    observacao character varying(255),
    preco_unitario numeric(10,2) NOT NULL,
    produto_id bigint NOT NULL,
    produto_nome character varying(200) NOT NULL,
    quantidade integer NOT NULL,
    pedido_id bigint NOT NULL
);


--
-- Name: itens_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.itens_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedidos (
    id bigint NOT NULL,
    cozinheiro_id bigint,
    cozinheiro_nome character varying(100),
    created_at timestamp(6) without time zone,
    entrega_id bigint,
    observacao character varying(255),
    ready_at timestamp(6) without time zone,
    restaurante_id bigint NOT NULL,
    status character varying(255),
    comanda_id bigint NOT NULL,
    CONSTRAINT pedidos_status_check CHECK (((status)::text = ANY ((ARRAY['ENVIADO'::character varying, 'PREPARANDO'::character varying, 'PRONTO'::character varying, 'ENTREGUE'::character varying])::text[])))
);


--
-- Name: pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurante_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.restaurante_configs (
    id bigint NOT NULL,
    comissao_cozinheiro numeric(5,2),
    comissao_entregador numeric(5,2),
    comissao_garcon numeric(5,2),
    pix_chave character varying(200),
    restaurante_id bigint NOT NULL
);


--
-- Name: restaurante_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.restaurante_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurante_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comandas comandas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comandas
    ADD CONSTRAINT comandas_pkey PRIMARY KEY (id);


--
-- Name: entregas entregas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entregas
    ADD CONSTRAINT entregas_pkey PRIMARY KEY (id);


--
-- Name: itens_entrega itens_entrega_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_entrega
    ADD CONSTRAINT itens_entrega_pkey PRIMARY KEY (id);


--
-- Name: itens_pedido itens_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_pedido
    ADD CONSTRAINT itens_pedido_pkey PRIMARY KEY (id);


--
-- Name: pedidos pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id);


--
-- Name: restaurante_configs restaurante_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurante_configs
    ADD CONSTRAINT restaurante_configs_pkey PRIMARY KEY (id);


--
-- Name: restaurante_configs uk481oi0oir5l30fy8oiplrbc8g; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurante_configs
    ADD CONSTRAINT uk481oi0oir5l30fy8oiplrbc8g UNIQUE (restaurante_id);


--
-- Name: itens_entrega fk1vthk52p2715d8gwau48dcsc3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_entrega
    ADD CONSTRAINT fk1vthk52p2715d8gwau48dcsc3 FOREIGN KEY (entrega_id) REFERENCES public.entregas(id);


--
-- Name: itens_pedido fk42mycompce3b7yt3l6ukdwsxy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_pedido
    ADD CONSTRAINT fk42mycompce3b7yt3l6ukdwsxy FOREIGN KEY (pedido_id) REFERENCES public.pedidos(id);


--
-- Name: pedidos fkt39xl9h0m4akhi3jvki0e94bv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fkt39xl9h0m4akhi3jvki0e94bv FOREIGN KEY (comanda_id) REFERENCES public.comandas(id);


--
-- PostgreSQL database dump complete
--


