CREATE TABLE despesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    valor NUMERIC(10,2) NOT NULL,
    data DATE NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT despesas_categoria_check CHECK (categoria IN ('ALUGUEL', 'INSUMOS', 'SALARIOS', 'ENERGIA', 'MANUTENCAO', 'OUTROS'))
);

CREATE INDEX idx_despesas_restaurante_id ON despesas (restaurante_id);
CREATE INDEX idx_despesas_restaurante_data ON despesas (restaurante_id, data);
