CREATE TABLE pausas_funcionamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    titulo VARCHAR(200),
    motivo VARCHAR(500),
    inicio TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    fim TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pausas_funcionamento_tipo_check CHECK (tipo IN ('PROGRAMADA', 'ENCERRAMENTO_ANTECIPADO'))
);

CREATE INDEX idx_pausas_funcionamento_restaurante_id ON pausas_funcionamento (restaurante_id);
CREATE INDEX idx_pausas_funcionamento_restaurante_fim ON pausas_funcionamento (restaurante_id, fim);
