CREATE TABLE horarios_funcionamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    hora_abertura TIME(6) WITHOUT TIME ZONE NOT NULL,
    hora_fechamento TIME(6) WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT horarios_funcionamento_dia_semana_check CHECK (dia_semana IN
        ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

CREATE INDEX idx_horarios_funcionamento_restaurante_id ON horarios_funcionamento (restaurante_id);
