-- Baseline gerada a partir de pg_dump --schema-only real (oia-postgres/db_whatsapp), substituindo a versao inferida anterior.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: itens_carrinho; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.itens_carrinho (
    id bigint NOT NULL,
    preco_unitario numeric(10,2) NOT NULL,
    produto_id bigint NOT NULL,
    produto_nome character varying(200) NOT NULL,
    quantidade integer NOT NULL,
    sessao_id bigint NOT NULL
);


--
-- Name: itens_carrinho_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.itens_carrinho ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_carrinho_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensagem_template; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mensagem_template (
    id bigint NOT NULL,
    ativo boolean,
    chave character varying(255) NOT NULL,
    grupo character varying(30),
    label character varying(150),
    ordem integer,
    restaurante_id bigint NOT NULL,
    texto text NOT NULL
);


--
-- Name: mensagem_template_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mensagem_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensagem_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessoes_whatsapp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessoes_whatsapp (
    id bigint NOT NULL,
    categoria_selecionada_id bigint,
    cliente_nome character varying(100),
    endereco_bairro character varying(100),
    endereco_cidade character varying(100),
    endereco_complemento character varying(100),
    endereco_numero character varying(20),
    endereco_rua character varying(200),
    entrega_id bigint,
    erros_consecutivos integer,
    estado character varying(255),
    metodo_pagamento character varying(30),
    observacao character varying(500),
    produto_selecionado_id bigint,
    restaurante_id bigint NOT NULL,
    telefone character varying(30) NOT NULL,
    ultima_interacao timestamp(6) without time zone,
    CONSTRAINT sessoes_whatsapp_estado_check CHECK (((estado)::text = ANY ((ARRAY['INICIO'::character varying, 'COLETANDO_NOME'::character varying, 'COLETANDO_ENDERECO_RUA'::character varying, 'COLETANDO_ENDERECO_NUMERO'::character varying, 'COLETANDO_ENDERECO_BAIRRO'::character varying, 'COLETANDO_ENDERECO_CIDADE'::character varying, 'COLETANDO_ENDERECO_COMPLEMENTO'::character varying, 'COLETANDO_ENDERECO'::character varying, 'NAVEGANDO_CATEGORIAS'::character varying, 'NAVEGANDO_PRODUTOS'::character varying, 'AGUARDANDO_QUANTIDADE'::character varying, 'REVISANDO_CARRINHO'::character varying, 'COLETANDO_PAGAMENTO'::character varying, 'COLETANDO_OBSERVACAO'::character varying, 'CONFIRMANDO_PEDIDO'::character varying, 'PEDIDO_ENVIADO'::character varying, 'AGUARDANDO_PIX'::character varying, 'PAUSADO'::character varying])::text[])))
);


--
-- Name: sessoes_whatsapp_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sessoes_whatsapp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessoes_whatsapp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itens_carrinho itens_carrinho_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_carrinho
    ADD CONSTRAINT itens_carrinho_pkey PRIMARY KEY (id);


--
-- Name: mensagem_template mensagem_template_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensagem_template
    ADD CONSTRAINT mensagem_template_pkey PRIMARY KEY (id);


--
-- Name: sessoes_whatsapp sessoes_whatsapp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessoes_whatsapp
    ADD CONSTRAINT sessoes_whatsapp_pkey PRIMARY KEY (id);


--
-- Name: mensagem_template ukln99p1h9r9bccgr64jh60viuj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensagem_template
    ADD CONSTRAINT ukln99p1h9r9bccgr64jh60viuj UNIQUE (restaurante_id, chave);


--
-- Name: itens_carrinho fkmaupr9e3itqv7djbmq0ulmpn1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.itens_carrinho
    ADD CONSTRAINT fkmaupr9e3itqv7djbmq0ulmpn1 FOREIGN KEY (sessao_id) REFERENCES public.sessoes_whatsapp(id);


--
-- PostgreSQL database dump complete
--


