-- Histórico persistido de mensagens trocadas via WhatsApp (ENVIADA pelo bot/admin,
-- RECEBIDA do cliente). Antes desta migration, apenas o estado da sessão era
-- persistido (sessoes_whatsapp) — o texto das mensagens em si não era guardado.
CREATE TABLE mensagens_whatsapp (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    direcao VARCHAR(20) NOT NULL CHECK (direcao IN ('ENVIADA', 'RECEBIDA')),
    texto VARCHAR(2000),
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_mensagens_whatsapp_restaurante_telefone_criado_em
    ON mensagens_whatsapp (restaurante_id, telefone, criado_em);
