-- Configuração operacional por restaurante do whatsapp-service. Hoje só
-- guarda o toggle de ativar/desativar o chatbot sem desconectar a instância
-- (a conexão com a Evolution API não depende deste flag).
CREATE TABLE whatsapp_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id  BIGINT NOT NULL,
    chatbot_ativo   BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_whatsapp_config_restaurante_id UNIQUE (restaurante_id)
);
