-- Baseline gerada a partir de pg_dump --schema-only real (oia-postgres/db_billing), substituindo a versao inferida anterior.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: contratos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contratos (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    data_inicio date NOT NULL,
    data_proximo_vencimento date,
    data_vencimento date,
    dias_carencia integer,
    mp_preapproval_id character varying(100),
    restaurante_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    plano_id bigint NOT NULL,
    CONSTRAINT contratos_status_check CHECK (((status)::text = ANY ((ARRAY['TRIAL'::character varying, 'ATIVO'::character varying, 'INADIMPLENTE'::character varying, 'BLOQUEADO'::character varying, 'CANCELADO'::character varying])::text[])))
);


--
-- Name: contratos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contratos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contratos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensagens_ticket; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mensagens_ticket (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    mensagem text NOT NULL,
    remetente_id bigint,
    remetente_nome character varying(100),
    remetente_tipo character varying(20),
    ticket_id bigint NOT NULL
);


--
-- Name: mensagens_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mensagens_ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensagens_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagamentos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pagamentos (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    data_pagamento date,
    metodo character varying(30),
    mp_payment_id character varying(100),
    observacao text,
    status character varying(20) NOT NULL,
    valor numeric(10,2) NOT NULL,
    contrato_id bigint NOT NULL,
    CONSTRAINT pagamentos_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'PAGO'::character varying, 'ESTORNADO'::character varying, 'FALHOU'::character varying])::text[])))
);


--
-- Name: pagamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pagamentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagamentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: planos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.planos (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    created_at timestamp(6) without time zone,
    descricao text,
    destaque boolean NOT NULL,
    dias_teste integer,
    funcionalidades text,
    limite_mesas integer,
    limite_usuarios integer,
    nome character varying(100) NOT NULL,
    periodo_teste boolean,
    preco_mensal numeric(10,2) NOT NULL
);


--
-- Name: planos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.planos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.planos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tickets_suporte; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tickets_suporte (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    descricao text NOT NULL,
    prioridade character varying(10) NOT NULL,
    resolvido_at timestamp(6) without time zone,
    restaurante_id bigint NOT NULL,
    restaurante_nome character varying(200),
    status character varying(20) NOT NULL,
    titulo character varying(200) NOT NULL,
    updated_at timestamp(6) without time zone,
    usuario_id bigint,
    CONSTRAINT tickets_suporte_prioridade_check CHECK (((prioridade)::text = ANY ((ARRAY['BAIXA'::character varying, 'MEDIA'::character varying, 'ALTA'::character varying, 'CRITICA'::character varying])::text[]))),
    CONSTRAINT tickets_suporte_status_check CHECK (((status)::text = ANY ((ARRAY['ABERTO'::character varying, 'EM_ANDAMENTO'::character varying, 'RESOLVIDO'::character varying, 'FECHADO'::character varying])::text[])))
);


--
-- Name: tickets_suporte_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tickets_suporte ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_suporte_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contratos contratos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT contratos_pkey PRIMARY KEY (id);


--
-- Name: mensagens_ticket mensagens_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensagens_ticket
    ADD CONSTRAINT mensagens_ticket_pkey PRIMARY KEY (id);


--
-- Name: pagamentos pagamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pagamentos
    ADD CONSTRAINT pagamentos_pkey PRIMARY KEY (id);


--
-- Name: planos planos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.planos
    ADD CONSTRAINT planos_pkey PRIMARY KEY (id);


--
-- Name: tickets_suporte tickets_suporte_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets_suporte
    ADD CONSTRAINT tickets_suporte_pkey PRIMARY KEY (id);


--
-- Name: contratos uk3q1qgoa509m5crdv1eu0t1cbb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT uk3q1qgoa509m5crdv1eu0t1cbb UNIQUE (restaurante_id);


--
-- Name: contratos fkgh457xtxh4blduv8fe6pejvs9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT fkgh457xtxh4blduv8fe6pejvs9 FOREIGN KEY (plano_id) REFERENCES public.planos(id);


--
-- Name: mensagens_ticket fkgsk7wilsqkn6q8g1lpm3nu5nl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensagens_ticket
    ADD CONSTRAINT fkgsk7wilsqkn6q8g1lpm3nu5nl FOREIGN KEY (ticket_id) REFERENCES public.tickets_suporte(id);


--
-- Name: pagamentos fkrkcg4f6rc0j8le2b7dsjoriuj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pagamentos
    ADD CONSTRAINT fkrkcg4f6rc0j8le2b7dsjoriuj FOREIGN KEY (contrato_id) REFERENCES public.contratos(id);


--
-- PostgreSQL database dump complete
--


