-- Registro de aceite do Contrato de Adesão/Termos de Uso/Política de
-- Privacidade — antes disso o checkbox de aceite era só uma trava do
-- front-end, nunca chegava no backend. Capturado no passo 1 do cadastro
-- (registro-iniciar, quando o usuário de fato clica aceitar) e copiado pra
-- um registro permanente quando a conta é criada de verdade (passo 2,
-- depois da verificação de e-mail — o registro_pendente é apagado nesse
-- momento, então o aceite não pode viver só nele).
ALTER TABLE registros_pendentes ADD COLUMN versao_contrato_aceito VARCHAR(20);
ALTER TABLE registros_pendentes ADD COLUMN aceito_em TIMESTAMP;
ALTER TABLE registros_pendentes ADD COLUMN ip_aceite VARCHAR(45);

CREATE TABLE aceites_contrato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    restaurante_id BIGINT NOT NULL,
    versao_contrato VARCHAR(20) NOT NULL,
    aceito_em TIMESTAMP NOT NULL,
    ip_aceite VARCHAR(45),
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_aceites_contrato_usuario ON aceites_contrato(usuario_id);
