-- Baseline gerada a partir de pg_dump --schema-only real (oia-postgres/db_auth), substituindo a versao inferida anterior.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: email_verificacoes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_verificacoes (
    id bigint NOT NULL,
    codigo character varying(6) NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(150) NOT NULL,
    expirado_em timestamp(6) without time zone NOT NULL,
    usado boolean NOT NULL
);


--
-- Name: email_verificacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_verificacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verificacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registros_pendentes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registros_pendentes (
    id bigint NOT NULL,
    cnpj character varying(18),
    created_at timestamp(6) without time zone,
    email character varying(150) NOT NULL,
    expirado_em timestamp(6) without time zone NOT NULL,
    nome_admin character varying(100) NOT NULL,
    nome_restaurante character varying(200) NOT NULL,
    plano_id bigint,
    senha_hash character varying(255) NOT NULL,
    telefone character varying(20)
);


--
-- Name: registros_pendentes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registros_pendentes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registros_pendentes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurantes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.restaurantes (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    bloqueado boolean NOT NULL,
    cnpj character varying(18),
    created_at timestamp(6) without time zone,
    data_bloqueio timestamp(6) without time zone,
    email_responsavel character varying(150),
    nome character varying(200) NOT NULL,
    plano character varying(20),
    slug character varying(100) NOT NULL,
    telefone character varying(20),
    whatsapp_instance_name character varying(100)
);


--
-- Name: restaurantes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.restaurantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(100) NOT NULL,
    email_verificado boolean,
    nome character varying(100) NOT NULL,
    role character varying(20) NOT NULL,
    senha character varying(255) NOT NULL,
    restaurante_id bigint,
    CONSTRAINT usuarios_role_check CHECK (((role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'ADMIN'::character varying, 'GARCON'::character varying, 'COZINHA'::character varying, 'ENTREGADOR'::character varying, 'CAIXA'::character varying])::text[])))
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_verificacoes email_verificacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verificacoes
    ADD CONSTRAINT email_verificacoes_pkey PRIMARY KEY (id);


--
-- Name: registros_pendentes registros_pendentes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_pendentes
    ADD CONSTRAINT registros_pendentes_pkey PRIMARY KEY (id);


--
-- Name: restaurantes restaurantes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurantes
    ADD CONSTRAINT restaurantes_pkey PRIMARY KEY (id);


--
-- Name: restaurantes uk9rdmuv8pdt7wq9c8yqybnbgtp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurantes
    ADD CONSTRAINT uk9rdmuv8pdt7wq9c8yqybnbgtp UNIQUE (slug);


--
-- Name: registros_pendentes ukddllg5ujo7sdshhlc392px7bp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registros_pendentes
    ADD CONSTRAINT ukddllg5ujo7sdshhlc392px7bp UNIQUE (email);


--
-- Name: usuarios ukkfsp0s1tflm1cwlj8idhqsad0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);


--
-- Name: restaurantes ukn8hwjiiuspenjyyyc0d8pmrpl; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restaurantes
    ADD CONSTRAINT ukn8hwjiiuspenjyyyc0d8pmrpl UNIQUE (whatsapp_instance_name);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: usuarios fk396qtxwodge9uffa2s4vrevy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT fk396qtxwodge9uffa2s4vrevy FOREIGN KEY (restaurante_id) REFERENCES public.restaurantes(id);


--
-- PostgreSQL database dump complete
--


