-- Grupos de permissão granular — camada adicional ao Papel (role) fixo do
-- usuário. Quando um usuário tem um grupo atribuído, as permissões do grupo
-- passam a definir o que ele acessa (ver JwtAuthFilter em cada serviço).
CREATE TABLE grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE grupo_permissoes (
    grupo_id BIGINT NOT NULL REFERENCES grupos(id) ON DELETE CASCADE,
    permissao VARCHAR(40) NOT NULL
);

CREATE INDEX idx_grupo_permissoes_grupo_id ON grupo_permissoes (grupo_id);
CREATE INDEX idx_grupos_restaurante_id ON grupos (restaurante_id);

ALTER TABLE usuarios ADD COLUMN grupo_id BIGINT REFERENCES grupos(id) ON DELETE SET NULL;
