-- Baseline gerada a partir de pg_dump --schema-only real (oia-postgres/db_table), substituindo a versao inferida anterior.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: mesas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mesas (
    id bigint NOT NULL,
    capacidade integer,
    numero integer NOT NULL,
    restaurante_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT mesas_status_check CHECK (((status)::text = ANY ((ARRAY['DISPONIVEL'::character varying, 'OCUPADA'::character varying, 'AGUARDANDO_PAGAMENTO'::character varying])::text[])))
);


--
-- Name: mesas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mesas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mesas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mesas mesas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mesas
    ADD CONSTRAINT mesas_pkey PRIMARY KEY (id);


--
-- Name: mesas uk285ohja65sto0qjaodvmufa0t; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mesas
    ADD CONSTRAINT uk285ohja65sto0qjaodvmufa0t UNIQUE (restaurante_id, numero);


--
-- PostgreSQL database dump complete
--


